# -*- coding: utf-8 -*-
"""Soal_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13okiAD9P7Ew-mduA6gaycw_UrlEFMgxN
"""

!pip install experta

!pip install --upgrade frozendict

from experta import *

class IdentifikasiHama(KnowledgeEngine):
    def __init__(self):
        super().__init__()
        self.diagnosis = []

    @Rule(Fact(daun_menguning=True))
    def hama_kutu_daun(self):
        self.diagnosis.append("Kemungkinan terkena serangan Kutu Daun.")

    @Rule(Fact(bercak_hitam=True))
    def hama_jamur_patogen(self):
        self.diagnosis.append("Kemungkinan terkena serangan Jamur Patogen.")

    @Rule(Fact(daun_berlubang=True))
    def hama_ulat_daun(self):
        self.diagnosis.append("Kemungkinan terkena serangan Ulat Daun.")

    @Rule(Fact(tanaman_layu=True))
    def hama_nematoda_tanah(self):
        self.diagnosis.append("Kemungkinan terkena serangan Nematoda Tanah.")

    @Rule()
    def selesai(self):
        print("\n--- Hasil Identifikasi ---")
        if self.diagnosis:
            for d in self.diagnosis:
                print("Diagnosa:", d)
        else:
            print("Maaf, gejala tidak sesuai dengan hama yang diketahui.")

def get_input():
    """Fungsi untuk mendapatkan input gejala dari pengguna."""
    def tanya(pertanyaan):
        return input(pertanyaan + " (ya/tidak): ").strip().lower() == "ya"

    return {
        "daun_menguning": tanya("Apakah daun tanaman menguning?"),
        "bercak_hitam": tanya("Apakah terdapat bercak hitam di daun?"),
        "daun_berlubang": tanya("Apakah daun tanaman berlubang?"),
        "tanaman_layu": tanya("Apakah tanaman tampak layu?")
    }

if __name__ == "__main__":
    print("=== Sistem Pakar: Identifikasi Hama Tanaman ===\n")
    gejala = get_input()
    mesin = IdentifikasiHama()
    mesin.reset()

    for gejala_nama, ada in gejala.items():
        mesin.declare(Fact(**{gejala_nama: ada}))

    mesin.run()